# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-06-01 21:15:22
"""
import arcpy

def SoilErase():  # Soil Erase

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    basin = "basin"
    soils = "soils"

    # Process: Clip (Clip) (analysis)
    soils_Basin_Clip = "C:\\Users\\Admin\\PycharmProjects\\UWF\\Module_3\\Data\\Mod3_Data\\Mod3_NAB\\Mod3_NAB.gdb\\soils__Basin_Clip"
    arcpy.analysis.Clip(in_features=soils, clip_features=basin, out_feature_class=soils_Basin_Clip, cluster_tolerance="")

    # Process: Select (Select) (analysis)
    soils_Basin_Clip_Select = "C:\\Users\\Admin\\PycharmProjects\\UWF\\Module_3\\Data\\Mod3_Data\\Mod3_NAB\\Mod3_NAB.gdb\\soils__Basin_Clip_Select"
    arcpy.analysis.Select(in_features=soils_Basin_Clip, out_feature_class=soils_Basin_Clip_Select, where_clause="FARMLNDCL = 'Not prime farmland'")

    # Process: Erase (Erase) (analysis)
    basin_EraseNotPrimeFarm = "C:\\Users\\Admin\\PycharmProjects\\UWF\\Module_3\\Data\\Mod3_Data\\Mod3_NAB\\Mod3_NAB.gdb\\basin_EraseNotPrimeFarm"
    arcpy.analysis.Erase(in_features=basin, erase_features=soils_Basin_Clip_Select, out_feature_class=basin_EraseNotPrimeFarm, cluster_tolerance="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Admin\PycharmProjects\UWF\Module_3\Data\Mod3_Data\Mod3_NAB\Mod3_NAB.gdb", workspace=r"C:\Users\Admin\PycharmProjects\UWF\Module_3\Data\Mod3_Data\Mod3_NAB\Mod3_NAB.gdb"):
        SoilErase()
